# This is the complete Dockerfile for the first example in the video
# Example 1
FROM golang:1.16 AS builder

WORKDIR /go/src/echo-go

COPY go.mod *.go ./

RUN go get -d -v
RUN go test -v

# need to use the CGO_ENABLED=0 to disably dynamic linking used by the net library
RUN CGO_ENABLED=0 GOOS=linux go build .


# Create target container from "scratch"
FROM scratch
COPY --from=builder /go/src/echo-go/echoapp /echoapp

EXPOSE 8081

CMD ["/echoapp"]